version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: bd_proj_e2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data:/docker-entrypoint-initdb.d